In [2]:
import pandas as pd

data = {
    "name" : ["A", "B", "C"],
    "age" : [20, 30, 40],
    "Salary" : [5000, 6000, 7000]
}

df = pd.DataFrame(data)
df

  name  age  Salary
0    A   20    5000
1    B   30    6000
2    C   40    7000

In [3]:
df.head()
df.describe()

        age  Salary
count   3.0     3.0
mean   30.0  6000.0
std    10.0  1000.0
min    20.0  5000.0
25%    25.0  5500.0
50%    30.0  6000.0
75%    35.0  6500.0
max    40.0  7000.0